Arguments: 
  /home/cehinon/.nvm/versions/node/v14.16.1/bin/node /mnt/c/Program Files (x86)/Yarn/bin/yarnpkg install

PATH: 
  /home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/cehinon/.nvm/versions/node/v14.16.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/Microsoft MPI/Bin/:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS/:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS/:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/nodejs/:/mnt/c/Program Files (x86)/Yarn/bin/:/mnt/c/TDM-GCC-32/bin:/mnt/c/Users/Cam's XPS/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Cam's XPS/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/Cam's XPS/AppData/Roaming/npm:/mnt/c/Users/Cam's XPS/AppData/Local/Yarn/bin:/mnt/c/Users/Cam's XPS/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0/LocalCache/local-packages/Python37/Scripts:/snap/bin

Yarn version: 
  1.21.1

Node version: 
  14.16.1

Platform: 
  linux x64

Trace: 
  Error: unexpected end of file
      at Zlib.zlibOnError [as onerror] (zlib.js:181:17)

npm manifest: 
  {
    "main": "node_modules/expo/AppEntry.js",
    "scripts": {
      "start": "expo start",
      "android": "expo start --android",
      "ios": "expo start --ios",
      "web": "expo start --web",
      "eject": "expo eject"
    },
    "dependencies": {
      "expo": "~42.0.1",
      "expo-status-bar": "~1.0.4",
      "react": "16.13.1",
      "react-dom": "16.13.1",
      "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
      "react-native-web": "~0.13.12"
    },
    "devDependencies": {
      "@babel/core": "^7.9.0"
    },
    "private": true
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile
